### ISSUE TITLE
Licensing on this?

### ISSUE THREAD

**Issue by furtabs** [fishcute/Noooooo#1]
Just curious since I want to fork and change the sound

**Comment by fishcute** [comment]
I probably should figure out licensing, but if you want to change the sound, you can just use a resource pack. The sound is located at `sounds/noooo.ogg` (At least for current versions, not sure about older versions). If that doesn't help you, feel free to change whatever you want. If you intend on releasing it as a standalone mod, credit would be appreciated.
If you need anything else, let me know. Not sure if I should've closed this yet.

**Comment by fishcute** [comment]
Oh whoops, ignore this

**Comment by furtabs** [comment]
I need a license file on the repo to legally be able to modify the code. 

*I'm, not a lawyer

MIT essentially means do what the fuck you want

GPL3 on the other hand means everything done with a GPL thing needs to be open source also under GPL

There are tons in between aswell. Dont feel like you have too tho

**Comment by fishcute** [comment]
Alright, sorry for the confusion. I'll figure something out soon.

**Comment by fishcute** [comment]
Alright, I think I added a license. If something isn't right, feel free to let me know.
